name: didar
description: "Custom Audio Player Flutter Project by shervin.hz07@gmail.com"
version: 1.0.0+1
homepage: https://github.com/shervin-h/didar
repository: https://github.com/shervin-h/didar
issue_tracker: https://github.com/shervin-h/didar/issues

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  just_audio: ^0.9.46
  dio: ^5.8.0+1
  path_provider: ^2.1.5
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Vazir
      fonts:
        - asset: assets/vazir_medium.ttf
